### ISSUE TITLE
unable to load secure.yaml: no secure.yml file found

### ISSUE THREAD

**Issue by rudexi** [terraform-provider-openstack/terraform-provider-openstack#1160]
Hi,

When upgrading terraform openstack provider from 1.35.0 to 1.36.0, I experienced the following issue:
```
Error: unable to load secure.yaml: no secure.yml file found
```

This is likely due to the upgrade of the gophercloud/utils version that happened between the two versions.

### Terraform Version
```
$terraform -v
Terraform v0.14.0
+ provider registry.terraform.io/rudexi/isilon v0.1.2
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.36.0

Your version of Terraform is out of date! The latest version
is 0.14.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

Provider

### Terraform Configuration Files

I was able to reproduce it with the following environment:
`main.tf`:
```hcl
provider "openstack" {
  cloud = "cloud1"
}

data "openstack_identity_project_v3" "test" {
  name = "test"
}

terraform {
  required_providers {
    openstack = {
      source = "terraform-provider-openstack/openstack"
      version = "1.36.0"
    }
  }
}
```

`clouds.yaml` (redacted):
```yaml
---
clouds:
    cloud1:
        auth:
            auth_url: https://keystone.cloud1.example.com:5000/v3
            project_name: test
            project_domain_name: cloud1.example.com
            user_domain_name: cloud1.example.com
            domain_name: cloud1.example.com
        region_name: CLOUD
        interface: public
        cacert: /etc/pki/tls/cert.pem
        identity_api_version: 3
    cloud2:
        auth:
            auth_url: https://keystone.cloud2.example.com:5000/v3
            project_name: test
            project_domain_name: cloud2.example.com
            user_domain_name: cloud2.example.com
            domain_name: cloud2.example.com
        region_name: CLOUD
        interface: public
        cacert: /etc/pki/tls/cert.pem
        identity_api_version: 3
```

The environment variables `OS_USERNAME` and `OS_PASSWORD` were set.

### Expected Behavior

When using the provider version `1.35.0`, it gave the expected result:
```
$terraform plan

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

### Actual Behavior

```
$terraform plan

Error: unable to load secure.yaml: no secure.yml file found

  on main.tf line 1, in provider "openstack":
   1: provider "openstack" {
```

### Steps to Reproduce

1) Prepare main.tf, clouds.yaml corresponding to your cloud instance
2) Set the `OS_USERNAME` and `OS_PASSWORD` environment variables
3) terraform init
4) terraform plan
