### ISSUE TITLE
Ability to use v3oidcclientcredentials for keystone authentication (auth_type)

### ISSUE THREAD

**Issue by dmsimard** [terraform-provider-openstack/terraform-provider-openstack#1827]
### Terraform Version
``OpenTofu v1.7.2`` (although not relevant to this issue)

### Affected Resource(s)
Provider authentication (every resource?)

### Terraform Configuration Files
```hcl
# For example
terraform {
  required_version = ">= 0.14.0"
  required_providers {
    openstack = {
      source  = "terraform-provider-openstack/openstack"
        version = "~> 3.0.0"
      }
  }
}

provider "openstack" {
  cloud = "ovhcloud"
}

resource "openstack_networking_secgroup_v2" "ssh" {
  name        = "ssh"
  description = "allow ssh"
}
```

### Debug Output
https://gist.githubusercontent.com/dmsimard/06c3d95332d29590bab436a946aa381e/raw/b984b586af18e26d9765f5d19542e8227c9448e7/openstack-debug.txt

### Panic Output
n/a

### Expected Behavior
Authentication with keystone using OIDC works as it does with openstackclient CLI.

### Actual Behavior
Authentication does not work:
```console
Error: Error creating OpenStack networking client: You must provide a password to authenticate
```

### Steps to Reproduce
Use the provided example HCL using an openrc that looks like this:
```bash
export OS_AUTH_TYPE=v3oidcclientcredentials
export OS_PROTOCOL=openid
export OS_ACCESS_TOKEN_TYPE=id_token
export OS_OPENID_SCOPE="openid profile email publicCloudProject/all"
export OS_AUTH_URL=https://auth.cloud.ovh.net/v3

export OS_IDENTITY_PROVIDER=ovhcloud-emea
export OS_DISCOVERY_ENDPOINT=https://iam.ovh.net/role-adapter/urn:v1:eu:resource:publicCloudProject:pci/.well-known/openid-configuration

export OS_PROJECT_ID=some-project
export OS_CLIENT_ID=some-id
export OS_CLIENT_SECRET=some-secret
export OS_REGION_NAME=some-region
```
an equivalent clouds.yaml would look like this:
```yaml
clouds:
  ovhcloud:
    auth_type: v3oidcclientcredentials
    region_name: some-region
    auth:
      protocol: "openid"
      access_token_type: "id_token"
      openid_scope: "openid profile email publicCloudProject/all"
      auth_url: "https://auth.cloud.ovh.net/v3"
      client_id: some-id
      client_secret: some-secret
      project_id: some-project
      discovery_endpoint: "https://iam.ovh.net/role-adapter/urn:v1:eu:resource:publicCloudProject:pci/.well-known/openid-configuration"
      identity_provider: "ovhcloud-emea"
```

Creating a user that we can use for this within the OVHcloud IAM is a bit convoluted so I won't go into the details here but there is documentation available here: https://github.com/ovh/docs/blob/develop/pages/manage_and_operate/iam/authenticate-api-openstack-with-service-account/guide.en-ca.md

If necessary, reach out to me and I can supply a user to reproduce this with.

### Important Factoids

I don't believe there is support for this in gophercloud which is probably where it should be implemented first.

There's some issues around the topic, notably:
- https://github.com/gophercloud/gophercloud/issues/966
- https://github.com/gophercloud/gophercloud/issues/1929
- https://github.com/gophercloud/utils/issues/197

### References
n/a
