### ISSUE TITLE
Terraform does not wait for cloud-init

### ISSUE THREAD

**Issue by Hoeze** [terraform-provider-openstack/terraform-provider-openstack#1828]
Hi, I just enabled package upgrading and rebooting if necessary in `cloud-init` to start with an up-to-date machine:
```yaml
package_update: true
package_upgrade: true
package_reboot_if_required: true
```
However, I noticed that terraform does not wait until the instance is actually up-to-date and rebooted.
This is problematic as I want to directly configure the instance with ansible when Terraform is done.

Is there a way to make Terraform wait until the instance is *actually* ready to be used?
